import { initializeApp } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js";
import { getAuth, signInAnonymously, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js";
import { getDatabase, ref, set, get, update, push, onValue, runTransaction } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-database.js";
import { firebaseConfig } from "./firebase-config.js";

const ROUND_SECONDS=90, MAX_ROUNDS=8, AP_PER_ROUND=3;
const $=id=>document.getElementById(id);
const clamp=v=>Math.max(0,Math.min(100,v));
const esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");

const NATIONS={
 auroria:{name:"아우로리아 연방",role:"군사 강국",desc:"강한 군사력이 안전을 보장한다고 믿지만 주변국은 그 힘 자체를 위협으로 받아들인다.",military:85,economy:58,influence:62,trust:38,stability:68,goals:[["군사력 88 이상",c=>c.military>=88],["영향력 65 이상",c=>c.influence>=65],["국내 안정도 55 이상",c=>c.stability>=55],["세계 긴장도 90 미만",c=>c.worldTension<90]]},
 belvar:{name:"벨바르 공화국",role:"경제 강국",desc:"시장과 무역망이 가장 강한 무기다. 세계 질서가 무너지면 가장 큰 손실도 감수해야 한다.",military:48,economy:88,influence:72,trust:63,stability:75,goals:[["경제력 82 이상",c=>c.economy>=82],["신뢰도 58 이상",c=>c.trust>=58],["국내 안정도 60 이상",c=>c.stability>=60],["세계 긴장도 72 미만",c=>c.worldTension<72]]},
 cyrene:{name:"키레네 왕국",role:"자원 강국",desc:"아르덴 해협과 에너지 자원을 쥐고 있다. 누구도 키레네를 무시할 수 없게 하는 것이 중요하다.",military:55,economy:70,influence:58,trust:52,stability:62,goals:[["경제력 76 이상",c=>c.economy>=76],["영향력 62 이상",c=>c.influence>=62],["국내 안정도 55 이상",c=>c.stability>=55],["동시 전쟁 상대 1개 이하",c=>c.warCount<=1]]},
 doran:{name:"도란 중립연합",role:"외교 강국",desc:"군사력은 약하지만 높은 국제 신뢰와 중재 능력을 지녔다.",military:36,economy:61,influence:84,trust:82,stability:78,goals:[["신뢰도 78 이상",c=>c.trust>=78],["영향력 78 이상",c=>c.influence>=78],["전쟁 선포 0회",c=>c.warsDeclared===0],["세계 긴장도 68 미만",c=>c.worldTension<68]]}
};

const STORY=[
 {title:"제1막 · 충돌",phase:"불안",event:"해협 경비정 충돌",body:"아르덴 해협에서 정체불명의 무장선과 경비정이 충돌했다. 사망자가 발생했지만 공격 주체는 확인되지 않았다.",base:3,choices:[["investigate","국제 공동조사를 요구한다","사실 확인을 우선하며 군사 대응을 자제한다.",{trust:4,influence:2,stability:-1,tension:-3}],["alert","군 경계태세를 올린다","추가 공격 가능성에 대비해 해협 인근 전력을 강화한다.",{military:3,economy:-2,trust:-3,stability:2,tension:6}],["silence","공식 대응을 보류한다","정보가 더 모일 때까지 입장을 내지 않는다.",{influence:-2,trust:-1,stability:1,tension:0}]]},
 {title:"제2막 · 선전전",phase:"의심",event:"민간인 피해 영상 확산",body:"민간 선박이 공격받는 영상이 전 세계에 퍼졌다. 영상은 일부 편집된 흔적이 있지만 이미 여론은 움직이기 시작했다.",base:4,choices:[["condemn","즉시 공격을 규탄한다","도덕적 책임을 강조하지만 사실관계가 틀릴 경우 역풍을 맞을 수 있다.",{influence:3,trust:1,stability:2,tension:3}],["verify","독립 검증을 요구한다","정보전 가능성을 경고하며 사실 검증을 우선한다.",{trust:4,influence:1,stability:-1,tension:-2}],["control","국내 보도를 통제한다","단기적 동요를 줄이지만 국제사회의 비판을 부를 수 있다.",{stability:5,trust:-5,influence:-2,tension:1}]]},
 {title:"제3막 · 에너지 위기",phase:"압박",event:"대형 유조선 피격",body:"해협 중앙에서 대형 유조선이 피격되며 원유 가격이 폭등했다. 경제 위기와 군사 위기가 하나로 얽히기 시작한다.",base:7,choices:[["escort","다국적 공동 호위를 제안한다","협력적 대응이지만 군함이 해협에 더 많이 모인다.",{influence:4,trust:3,economy:-2,tension:2}],["reserve","국가 비축분을 확대한다","국내 경제를 방어하지만 국제시장 불안을 키울 수 있다.",{economy:2,stability:4,influence:-1,tension:2}],["pressure","원유 공급국을 압박한다","가격 안정을 강제하려 하지만 외교 비용이 크다.",{economy:4,influence:1,trust:-5,tension:4}]]},
 {title:"제4막 · 동맹의 그림자",phase:"분열",event:"비밀 군사협정 문서 유출",body:"한 국가가 비밀 군사협정을 준비했다는 문서가 유출됐다. 진위는 확인되지 않았지만 각국의 의심은 커진다.",base:5,choices:[["disclose","모든 비밀 협정 공개를 요구한다","투명성을 요구해 신뢰 회복을 시도한다.",{trust:4,influence:3,tension:-2}],["backchannel","비밀 채널로 사실을 확인한다","공개 충돌은 피하지만 국내에서는 소극적으로 보일 수 있다.",{influence:2,stability:-2,trust:1,tension:-1}],["prepare","최악을 가정해 군사 대비한다","안보를 확보하지만 안보 딜레마를 심화시킨다.",{military:4,economy:-2,trust:-4,tension:7}]]},
 {title:"제5막 · 오인 경보",phase:"위기",event:"미사일 발사 경보",body:"조기경보망이 미사일 발사 징후를 포착했다. 몇 분 뒤 오인 가능성이 제기됐지만 군은 이미 대응 명령을 기다리고 있다.",base:10,choices:[["hotline","핫라인으로 즉시 사실을 확인한다","오판에 의한 전쟁 가능성을 크게 낮춘다.",{trust:5,influence:2,tension:-7,stability:-1}],["intercept","요격 및 보복 준비에 들어간다","억지력을 보여주지만 선제공격 준비로 오인될 수 있다.",{military:5,trust:-5,stability:3,tension:9}],["evacuate","대피령을 내리고 판단을 보류한다","국민 보호를 우선하지만 공포와 경제 충격이 커진다.",{stability:-3,economy:-4,trust:1,tension:2}]]},
 {title:"제6막 · 시장 붕괴",phase:"붕괴",event:"국제 금융시장 급락",body:"전쟁 우려로 금융시장과 에너지 시장이 동시에 폭락했다. 이제 국가 내부를 버티게 하는 문제도 중요해졌다.",base:5,choices:[["fund","국제 시장안정기금을 제안한다","자원을 투입해 시장을 떠받치고 협력 체제를 강화한다.",{economy:-2,influence:5,trust:4,stability:2,tension:-3}],["protect","보호무역 조치를 발동한다","국내 산업을 보호하지만 보복을 부를 수 있다.",{economy:3,stability:4,trust:-5,influence:-2,tension:3}],["austerity","긴축과 비상예산을 실시한다","재정을 방어하지만 국민 불만이 커진다.",{economy:4,stability:-5,influence:-1,tension:0}]]},
 {title:"제7막 · 핵 그림자",phase:"극한",event:"전술핵 배치 정보 유출",body:"전술핵이 전진 배치됐다는 정보가 공개됐다. 사실 여부보다 각국이 이를 믿기 시작한 것이 더 위험하다.",base:12,choices:[["armsTalk","긴급 군축 회담을 요구한다","상호 검증과 군축으로 공포의 악순환을 끊으려 한다.",{trust:6,influence:4,tension:-8,stability:-1}],["deterrence","전략 억지 태세를 강화한다","공격을 막기 위한 조치지만 군비 경쟁을 극대화한다.",{military:6,economy:-4,trust:-6,tension:10,stability:2}],["infoWar","상대의 핵 위협 정보를 공개한다","국제 여론을 얻으려 하지만 정보전이 통제 불능이 될 수 있다.",{influence:5,trust:-2,stability:1,tension:5}]]},
 {title:"최종막 · 마지막 정상회의",phase:"결단",event:"아르덴 긴급 정상회의",body:"각국 지도자가 마지막 정상회의에 모였다. 합의문이 나올 수도 있고 전쟁 전 마지막 사진으로 남을 수도 있다.",base:-2,choices:[["grandDeal","포괄적 평화 합의를 추진한다","일부 국익을 양보하는 대신 전쟁 위험을 크게 낮춘다.",{economy:-2,influence:5,trust:6,tension:-10,stability:-1}],["nationalDeal","자국 이익을 우선한 협상을 한다","국가적 성과를 노리지만 합의가 약해질 수 있다.",{economy:3,influence:3,trust:-2,tension:1,stability:2}],["walkAway","결렬에 대비해 회담장을 떠날 준비를 한다","양보는 피하지만 세계는 최악을 준비한다.",{military:2,trust:-6,influence:-3,tension:8,stability:3}]]}
];

let app,auth,db,user,roomCode,currentRoom,unsub,timer,lastMajorSeen=null,advanceLock=false;
const n=id=>NATIONS[id]; const story=r=>STORY[Math.max(0,Math.min(7,r-1))];
const toast=m=>{$("toast").textContent=m;$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),1800)};
const show=id=>["setupScreen","lobbyScreen","gameScreen","resultScreen"].forEach(x=>$(x).classList.toggle("active",x===id));
const code=()=>Array.from({length:6},()=>"ABCDEFGHJKLMNPQRSTUVWXYZ23456789"[Math.floor(Math.random()*32)]).join("");
const effectText=e=>{const m={military:"군사력",economy:"경제력",influence:"영향력",trust:"신뢰도",stability:"국내 안정도",tension:"세계 긴장도"};return Object.entries(e).filter(([,v])=>v).map(([k,v])=>`${m[k]} ${v>0?"+":""}${v}`).join(" · ")};

async function boot(){try{app=initializeApp(firebaseConfig);auth=getAuth(app);db=getDatabase(app);onAuthStateChanged(auth,u=>{if(u){user=u;$("authStatus").textContent="온라인"}});await signInAnonymously(auth)}catch(e){console.error(e);$("authStatus").textContent="Firebase 연결 오류"}}
async function createRoom(){if(!user)return;roomCode=code();const now=Date.now();await set(ref(db,`rooms/${roomCode}`),{meta:{hostUid:user.uid,status:"lobby"},world:{round:1,tension:25,ended:false},players:{[user.uid]:{name:$("playerName").value.trim()||"익명 외교관",nationId:"",ap:3,stats:{}}},feed:{start:{text:"협상장이 열렸습니다.",at:now}}});enter()}
async function joinRoom(){const c=$("roomCodeInput").value.trim().toUpperCase();const snap=await get(ref(db,`rooms/${c}`));if(!snap.exists())return toast("존재하지 않는 방입니다.");roomCode=c;await set(ref(db,`rooms/${c}/players/${user.uid}`),{name:$("playerName").value.trim()||"익명 외교관",nationId:"",ap:3,stats:{}});enter()}
function enter(){$("roomBadge").textContent=`ROOM ${roomCode}`;$("roomBadge").classList.remove("hidden");unsub?.();unsub=onValue(ref(db,`rooms/${roomCode}`),s=>render(s.val()))}
function render(room){if(!room)return;currentRoom=room;if(room.meta.status==="lobby"){show("lobbyScreen");renderLobby(room)}else if(room.world.ended||room.meta.status==="finished"){show("resultScreen");renderResult(room)}else{show("gameScreen");renderGame(room);startTimer()}}
function renderLobby(room){const ps=room.players||{},taken={};Object.entries(ps).forEach(([u,p])=>{if(p.nationId)taken[p.nationId]=u});$("nationCards").innerHTML=Object.entries(NATIONS).map(([id,x])=>`<div class="nation ${taken[id]===user.uid?"selected":""} ${taken[id]&&taken[id]!==user.uid?"taken":""}"><p class="eyebrow">${x.role}</p><h3>${x.name}</h3><p class="hint">${x.desc}</p><div class="stats"><span>군사 ${x.military}</span><span>경제 ${x.economy}</span><span>영향 ${x.influence}</span><span>신뢰 ${x.trust}</span></div><button data-nation="${id}" ${taken[id]&&taken[id]!==user.uid?"disabled":""}>${taken[id]===user.uid?"선택됨":"이 국가 선택"}</button></div>`).join("");document.querySelectorAll("[data-nation]").forEach(b=>b.onclick=()=>claim(b.dataset.nation));$("lobbyPlayers").innerHTML=Object.entries(ps).map(([u,p])=>`<div class="player-row"><strong>${esc(p.name)}</strong><div class="hint">${p.nationId?n(p.nationId).name:"국가 선택 중"}${u===room.meta.hostUid?" · 방장":""}</div></div>`).join("");const host=room.meta.hostUid===user.uid;$("startGameBtn").classList.toggle("hidden",!host);$("hostNotice").classList.toggle("hidden",host);$("startGameBtn").disabled=Object.keys(ps).length<2||Object.values(ps).some(p=>!p.nationId)}
async function claim(id){await runTransaction(ref(db,`rooms/${roomCode}`),r=>{if(!r)return r;const used=Object.entries(r.players).some(([u,p])=>u!==user.uid&&p.nationId===id);if(used)return;r.players[user.uid].nationId=id;return r})}
async function startGame(){const room=(await get(ref(db,`rooms/${roomCode}`))).val();if(room.meta.hostUid!==user.uid)return;const states={};for(const p of Object.values(room.players)){const x=n(p.nationId);states[p.nationId]={military:x.military,economy:x.economy,influence:x.influence,trust:x.trust,stability:x.stability,atWarWith:{}}}const st=story(1),now=Date.now();const up={"meta/status":"playing","world/round":1,"world/tension":25+st.base,"world/roundDeadline":now+90000,nationState:states};Object.keys(room.players).forEach(u=>up[`players/${u}/ap`]=3);await update(ref(db,`rooms/${roomCode}`),up);await push(ref(db,`rooms/${roomCode}/feed`),{type:"story",major:true,typeLabel:"메인 사건",text:`${st.event} — ${st.body}`,round:1,at:now})}
function renderGame(room){const me=room.players[user.uid],x=n(me.nationId),s=room.nationState[me.nationId],r=room.world.round,st=story(r);$("roundValue").textContent=`${r} / 8`;$("apValue").textContent=`${me.ap??0} / 3`;$("tensionValue").textContent=room.world.tension;$("tensionBar").style.width=`${clamp(room.world.tension)}%`;for(const [id,k] of [["trustValue","trust"],["influenceValue","influence"],["militaryValue","military"],["economyValue","economy"],["stabilityValue","stability"]])$(id).textContent=s[k];$("myNationCard").innerHTML=`<p class="eyebrow">${x.role}</p><h2>${x.name}</h2><p class="hint">메인 사건 선택은 AP를 소모하지 않습니다.</p>`;$("scenarioTitle").textContent=st.title;$("phaseBadge").textContent=st.phase;$("scenarioDesc").textContent=st.body;$("latestEvent").innerHTML=`<strong>${st.event}</strong><br>${st.body}`;const opts=Object.entries(room.players).filter(([u,p])=>u!==user.uid&&p.nationId).map(([,p])=>`<option value="${p.nationId}">${n(p.nationId).name} — ${esc(p.name)}</option>`).join("");["publicTarget","privateTarget","militaryTarget"].forEach(id=>$(id).innerHTML=opts||`<option>대상 없음</option>`);renderChoices(room,me,st);renderFeed(room.feed||{});renderWorld(room);renderPrivate(room,me);renderGoals(room,me);renderOutcome(me);showMajor(room.feed||{});document.querySelectorAll("[data-action]").forEach(b=>b.disabled=(me.ap??0)<(b.dataset.action==="war"?2:b.dataset.action==="statement"?0:1))}
function renderChoices(room,me,st){const done=room.eventChoices?.[room.world.round]?.[user.uid];$("choiceStatus").textContent=done?"선택 완료":"선택 필요";$("choiceStatus").classList.toggle("done",!!done);$("eventChoices").innerHTML=st.choices.map(c=>`<button ${done?"disabled":""} class="${done?.choiceId===c[0]?"chosen":""}" data-choice="${c[0]}"><strong>${c[1]}</strong><span>${c[2]}</span></button>`).join("");document.querySelectorAll("[data-choice]").forEach(b=>b.onclick=()=>chooseEvent(b.dataset.choice));if(done){$("eventChoiceResult").classList.remove("hidden");$("eventChoiceResult").innerHTML=`<strong>${done.title}</strong><br>${done.resultText}`}else $("eventChoiceResult").classList.add("hidden")}
async function chooseEvent(id){await runTransaction(ref(db,`rooms/${roomCode}`),r=>{const me=r.players[user.uid],round=r.world.round;r.eventChoices=r.eventChoices||{};r.eventChoices[round]=r.eventChoices[round]||{};if(r.eventChoices[round][user.uid])return r;const c=story(round).choices.find(x=>x[0]===id);const e=c[3],s=r.nationState[me.nationId];for(const k of ["military","economy","influence","trust","stability"])if(e[k])s[k]=clamp(s[k]+e[k]);r.world.tension=clamp(r.world.tension+(e.tension||0));const txt=effectText(e);r.eventChoices[round][user.uid]={choiceId:id,title:c[1],resultText:txt};r.feed=r.feed||{};r.feed[`choice_${Date.now()}_${user.uid}`]={type:"eventChoice",typeLabel:"사건 대응",text:`${n(me.nationId).name} — ${c[1]}`,effectText:txt,round,at:Date.now()};me.lastOutcome={label:"메인 사건 대응",summary:`${c[1]}을 선택했습니다.`,effects:txt.split(" · ")};return r})}
function renderFeed(f){const a=Object.values(f).sort((a,b)=>(a.at||0)-(b.at||0));$("worldFeed").innerHTML=a.slice(-100).map(i=>`<div class="feed-item ${i.major?"major":""} ${i.type==="war"||i.type==="sanction"?"danger":""}"><div class="feed-meta">ROUND ${i.round||"-"} · ${i.typeLabel||"SYSTEM"}</div><div>${esc(i.text)}</div>${i.effectText?`<div class="effect-line">${esc(i.effectText)}</div>`:""}</div>`).join("")}
function renderWorld(room){$("worldStates").innerHTML=Object.values(room.players).filter(p=>p.nationId).map(p=>{const s=room.nationState[p.nationId];return `<div class="world-state"><div class="state-head"><strong>${n(p.nationId).name}</strong><span>${esc(p.name)}</span></div><div class="state-sub">군 ${s.military} · 경제 ${s.economy} · 영향 ${s.influence}</div><div class="state-sub">신뢰 ${s.trust} · 국내 안정 ${s.stability}</div></div>`}).join("")}
function renderPrivate(room,me){const a=Object.values(room.privateMessages||{}).filter(m=>m.from===me.nationId||m.to===me.nationId);$("privateInbox").innerHTML=a.map(m=>`<div class="private-msg"><div class="feed-meta">${n(m.from).name} → ${n(m.to).name}</div>${esc(m.text)}</div>`).join("")}
function ctx(room,me){const s=room.nationState[me.nationId];return {...s,worldTension:room.world.tension,warCount:Object.values(s.atWarWith||{}).filter(Boolean).length,warsDeclared:me.stats?.wars||0}}
function renderGoals(room,me){$("liveChecklist").innerHTML=n(me.nationId).goals.map(([t,f])=>`<div class="check-item ${f(ctx(room,me))?"ok":"no"}">${f(ctx(room,me))?"✓":"○"} ${t}</div>`).join("")}
function renderOutcome(me){if(!me.lastOutcome)return $("lastOutcome").classList.add("hidden");$("lastOutcome").classList.remove("hidden");$("lastOutcome").innerHTML=`<div class="outcome-title">최근 행동 결과 · ${me.lastOutcome.label}</div><div>${me.lastOutcome.summary}</div><div class="outcome-effects">${(me.lastOutcome.effects||[]).map(e=>`<span>${e}</span>`).join("")}</div>`}
async function spend(cost){if(!cost)return true;const r=await runTransaction(ref(db,`rooms/${roomCode}/players/${user.uid}/ap`),v=>(v??0)>=cost?v-cost:undefined);if(!r.committed)toast("행동력이 부족합니다.");return r.committed}
async function stat(k){await runTransaction(ref(db,`rooms/${roomCode}/players/${user.uid}/stats/${k}`),v=>(v||0)+1)}
async function outcome(label,summary,effects){await set(ref(db,`rooms/${roomCode}/players/${user.uid}/lastOutcome`),{label,summary,effects})}
async function publicAction(a){const target=$("publicTarget").value;if(!target)return;const cost=a==="statement"?0:1;if(!(await spend(cost)))return;const room=(await get(ref(db,`rooms/${roomCode}`))).val(),me=room.players[user.uid],from=me.nationId,s=room.nationState[from],ts=room.nationState[target],up={};let label,text,e={},extra=[],major=false,summary="";if(a==="statement"){label="공식 성명";major=true;const tone=$("statementTone").value;e=tone==="reconcile"?{trust:3,influence:1,tension:-2}:tone==="hardline"?{influence:2,trust:-3,stability:2,tension:4}:{influence:2,trust:1};text=`${n(from).name}: “${$("publicMessage").value.trim()||"우리 국가는 상황을 예의주시하고 있다."}”`;summary="성명의 기조에 따라 신뢰·영향력·긴장도가 변했습니다.";await stat("statements")}else if(a==="treaty"){label="협정 제안";major=true;e={trust:2,influence:2,tension:-1};text=`${n(from).name}이(가) ${n(target).name}에 협정을 제안했다.`;summary="협력 의지를 보여 신뢰와 영향력이 상승했습니다.";await stat("treaties")}else if(a==="aid"){label="경제 원조";e={economy:-3,influence:4,trust:3,tension:-1};up[`nationState/${target}/economy`]=clamp(ts.economy+5);up[`nationState/${target}/stability`]=clamp(ts.stability+3);extra=[`${n(target).name} 경제력 +5`,`${n(target).name} 국내 안정도 +3`];text=`${n(from).name}이(가) ${n(target).name}에 경제 원조를 제공했다.`;summary="자국 자원을 지출하는 대신 상대의 경제와 안정, 자국의 영향력을 높였습니다.";await stat("aid")}else{label="경제 제재";major=true;e={influence:2,trust:-4,tension:5};up[`nationState/${target}/economy`]=clamp(ts.economy-6);up[`nationState/${target}/stability`]=clamp(ts.stability-4);extra=[`${n(target).name} 경제력 -6`,`${n(target).name} 국내 안정도 -4`];text=`${n(from).name}이(가) ${n(target).name}에 경제 제재를 발표했다.`;summary="상대 경제와 국내 안정을 흔들었지만 국제 긴장과 불신을 키웠습니다.";await stat("sanctions")}for(const k of ["military","economy","influence","trust","stability"])if(e[k])up[`nationState/${from}/${k}`]=clamp(s[k]+e[k]);up["world/tension"]=clamp(room.world.tension+(e.tension||0));await update(ref(db,`rooms/${roomCode}`),up);const effects=[...effectText(e).split(" · ").filter(Boolean),...extra];await outcome(label,summary,effects);await push(ref(db,`rooms/${roomCode}/feed`),{type:a,typeLabel:label,text,effectText:effects.join(" · "),major,round:room.world.round,at:Date.now()});$("publicMessage").value=""}
async function military(a){const target=$("militaryTarget").value,cost=a==="war"?2:1;if(!(await spend(cost)))return;const room=(await get(ref(db,`rooms/${roomCode}`))).val(),me=room.players[user.uid],from=me.nationId,s=room.nationState[from],ts=room.nationState[target],up={};let label,text,effects,summary;if(a==="deploy"){label="국경 병력 증강";up[`nationState/${from}/military`]=clamp(s.military+4);up[`nationState/${from}/economy`]=clamp(s.economy-2);up[`nationState/${from}/trust`]=clamp(s.trust-3);up[`nationState/${target}/stability`]=clamp(ts.stability-2);up["world/tension"]=clamp(room.world.tension+6);effects=["군사력 +4","경제력 -2","신뢰도 -3",`${n(target).name} 국내 안정도 -2`,`세계 긴장도 +6`];summary="억지력은 높아졌지만 유지 비용과 상대의 위협 인식이 커졌습니다.";await stat("military")}else if(a==="warning"){label="최후통첩";up[`nationState/${from}/influence`]=clamp(s.influence+2);up[`nationState/${from}/trust`]=clamp(s.trust-5);up[`nationState/${target}/stability`]=clamp(ts.stability-4);up["world/tension"]=clamp(room.world.tension+8);effects=["영향력 +2","신뢰도 -5",`${n(target).name} 국내 안정도 -4`,`세계 긴장도 +8`];summary="상대를 압박했지만 신뢰와 안정성을 크게 훼손했습니다.";await stat("military")}else{label="전쟁 선포";const al=Math.max(3,Math.round(ts.military/18)),dl=Math.max(4,Math.round(s.military/15));up[`nationState/${from}/atWarWith/${target}`]=true;up[`nationState/${target}/atWarWith/${from}`]=true;up[`nationState/${from}/military`]=clamp(s.military-al);up[`nationState/${target}/military`]=clamp(ts.military-dl);up[`nationState/${from}/economy`]=clamp(s.economy-7);up[`nationState/${target}/economy`]=clamp(ts.economy-9);up[`nationState/${from}/stability`]=clamp(s.stability-4);up[`nationState/${target}/stability`]=clamp(ts.stability-8);up[`nationState/${from}/trust`]=clamp(s.trust-12);up["world/tension"]=clamp(room.world.tension+20);effects=[`군사력 -${al}`,"경제력 -7","국내 안정도 -4","신뢰도 -12",`${n(target).name} 군사력 -${dl}`,`${n(target).name} 경제력 -9`,`${n(target).name} 국내 안정도 -8`,`세계 긴장도 +20`];summary="전쟁 비용이 양국의 군사·경제·국내 안정에 즉시 반영되었습니다.";await stat("wars")}text=`${n(from).name}이(가) ${n(target).name}에 ${label}${a==="war"?"했다":"을 실행했다"}.`;await update(ref(db,`rooms/${roomCode}`),up);await outcome(label,summary,effects);await push(ref(db,`rooms/${roomCode}/feed`),{type:a==="war"?"war":"military",typeLabel:label,text,effectText:effects.join(" · "),major:true,round:room.world.round,at:Date.now()})}
async function privateMsg(){const t=$("privateTarget").value,m=$("privateMessage").value.trim();if(!m)return;const room=(await get(ref(db,`rooms/${roomCode}`))).val(),from=room.players[user.uid].nationId;await push(ref(db,`rooms/${roomCode}/privateMessages`),{from,to:t,text:m,at:Date.now()});await stat("privateMessages");$("privateMessage").value="";toast("암호 전문을 전송했습니다.")}
function startTimer(){clearInterval(timer);timer=setInterval(async()=>{const r=currentRoom;if(!r||r.meta.status!=="playing")return;const left=Math.max(0,Math.ceil((r.world.roundDeadline-Date.now())/1000));$("timerValue").textContent=`${String(Math.floor(left/60)).padStart(2,"0")}:${String(left%60).padStart(2,"0")}`;const all=Object.values(r.players).every(p=>(p.ap??0)<=0);if((left<=0||all)&&r.meta.hostUid===user.uid&&!advanceLock){advanceLock=true;await advance();setTimeout(()=>advanceLock=false,1200)}},500)}
async function advance(){await runTransaction(ref(db,`rooms/${roomCode}`),r=>{if(!r||r.world.ended)return r;const now=Date.now(),round=r.world.round;if(round>=8){r.world.ended=true;r.meta.status="finished";return r}const nr=round+1,st=story(nr);r.world.round=nr;r.world.roundDeadline=now+90000;r.world.tension=clamp(r.world.tension+st.base);Object.values(r.players).forEach(p=>p.ap=3);r.feed=r.feed||{};r.feed[`story_${now}`]={type:"story",major:true,typeLabel:"메인 사건",text:`${st.event} — ${st.body}`,effectText:`세계 긴장도 ${st.base>0?"+":""}${st.base}`,round:nr,at:now};return r})}
function showMajor(feed){const a=Object.entries(feed).map(([id,x])=>({id,...x})).filter(x=>x.major).sort((a,b)=>(a.at||0)-(b.at||0));if(!a.length||a.at(-1).id===lastMajorSeen)return;const x=a.at(-1);lastMajorSeen=x.id;$("majorOverlayCard").className=`major-card ${x.type==="war"?"war":x.type==="story"?"story":"statement"}`;$("majorEyebrow").textContent=x.type==="war"?"WAR DECLARATION":x.type==="story"?"BREAKING STORY":"MAJOR ACTION";$("majorTitle").textContent=x.typeLabel;$("majorBody").textContent=x.text+(x.effectText?`\n\n${x.effectText}`:"");$("majorOverlay").classList.remove("hidden")}
function renderResult(room){const me=room.players[user.uid],x=n(me.nationId),c=ctx(room,me),s=room.nationState[me.nationId],goals=x.goals.map(([t,f])=>[t,f(c)]);$("resultTitle").textContent=`${x.name} · 최종 평가`;$("resultSummary").textContent=`국가 목표 ${goals.length}개 중 ${goals.filter(g=>g[1]).length}개를 달성했습니다. 세계 긴장도는 ${room.world.tension}으로 종료되었습니다.`;$("resultChecklist").innerHTML=goals.map(g=>`<div class="check-item ${g[1]?"ok":"no"}">${g[1]?"✓":"✕"} ${g[0]}</div>`).join("");const metrics=[["국가 안보",s.military],["경제 성과",s.economy],["국제 신뢰",s.trust],["외교 영향력",s.influence],["국내 안정",s.stability],["세계 안정",100-room.world.tension]];$("resultMetrics").innerHTML=metrics.map(([k,v])=>`<div class="metric"><div class="metric-head"><span>${k}</span><strong>${v}</strong></div><div class="metric-bar"><i style="width:${clamp(v)}%"></i></div></div>`).join("");const st=me.stats||{},co=(st.sanctions||0)+(st.military||0)+(st.wars||0)*2,cp=(st.treaties||0)+(st.aid||0)+(st.privateMessages||0)*.25;$("theoryAnalysis").textContent=co>cp*1.35?"현실주의적 경향이 강했습니다. 안보와 강압 수단을 우선하며 힘의 균형을 중시했습니다.":cp>co*1.35?"자유주의적 경향이 강했습니다. 협력, 원조, 외교 채널을 통해 상호의존과 신뢰를 높였습니다.":"협력과 강압을 병행한 혼합 전략에 가까웠습니다."}

$("createRoomBtn").onclick=createRoom;$("joinRoomBtn").onclick=joinRoom;$("startGameBtn").onclick=startGame;$("copyCodeBtn").onclick=()=>navigator.clipboard.writeText(roomCode);$("sendPrivateBtn").onclick=privateMsg;$("closeMajorBtn").onclick=()=>$("majorOverlay").classList.add("hidden");document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab,.tab-panel").forEach(x=>x.classList.remove("active"));b.classList.add("active");$(`${b.dataset.tab}Tab`).classList.add("active")});document.querySelectorAll("[data-action]").forEach(b=>b.onclick=()=>["statement","treaty","aid","sanction"].includes(b.dataset.action)?publicAction(b.dataset.action):military(b.dataset.action));boot();
