'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Globe2,Shield,Landmark,Users,Factory,Handshake,Coins,Clock3,Radio,LockKeyhole,Flag,Check,Copy,BookOpen,LogOut,Send,Activity,Trophy,AlertTriangle,ChevronDown} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Progress} from '@/components/ui/progress';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {AlertDialog,AlertDialogAction,AlertDialogCancel,AlertDialogContent,AlertDialogDescription,AlertDialogFooter,AlertDialogHeader,AlertDialogTitle} from '@/components/ui/alert-dialog';
import {ACTIONS,CHOICES,EVENTS,NATIONS,STAT_NAMES,RoomView,Stat,Command,canStart} from '@/lib/game';
type Input=Command&{code?:string};
const ICONS={economy:Landmark,support:Users,military:Shield,infrastructure:Factory,relations:Handshake};
const positions=[[43,24],[78,48],[57,77],[19,52]];
const territories=['M285 30 358 36 390 68 438 55 464 100 439 145 367 162 322 128 274 144 243 100Z','M495 132 564 102 619 130 667 120 705 171 672 216 705 248 624 283 572 250 514 262 487 205Z','M350 246 410 214 460 235 499 282 558 300 547 359 481 388 440 367 391 389 326 350 298 308Z','M55 160 107 127 160 151 219 139 257 182 238 215 278 254 221 281 188 317 136 296 107 254 55 240 32 196Z'];
function WorldMap({room,target,onTarget}:{room?:RoomView|null;target:number;onTarget:(n:number)=>void}){return <div className="world-map"><div className="map-heading"><span><Globe2 size={16}/> 아르덴 세계 지도</span><span>국가를 눌러 대상 선택</span></div><svg viewBox="0 0 740 420" role="img" aria-label="북부 아우로리아, 동부 벨바르, 남부 키레네, 서부 도란의 위치를 표시한 가상 세계 지도"><defs><pattern id="grid" width="35" height="35" patternUnits="userSpaceOnUse"><path d="M35 0H0V35" fill="none" stroke="#9baabb" strokeOpacity=".07"/></pattern></defs><rect width="740" height="420" fill="url(#grid)"/><ellipse cx="370" cy="210" rx="345" ry="185" fill="none" stroke="#526578" strokeOpacity=".2"/>{territories.map((d,n)=><path key={n} d={d} fill={NATIONS[n].color} fillOpacity={target===n?.24:.10} stroke={NATIONS[n].color} strokeOpacity={target===n?1:.4} strokeWidth={target===n?2:1}/>)}<path d="M145 215Q360 300 579 199M321 100Q415 180 422 325" fill="none" stroke="#8198ac" strokeDasharray="5 7" opacity=".22"/><text x="378" y="219" textAnchor="middle" fill="#72889a" fontSize="13" letterSpacing="4">아르덴 해협</text></svg>{NATIONS.map((n,i)=>{const p=room?.players.find(p=>p.nation===i);return <button key={i} className={`map-pin ${target===i?'chosen':''}`} style={{left:`${positions[i][0]}%`,top:`${positions[i][1]}%`,'--nation':n.color} as React.CSSProperties} disabled={!!room&&room.status!=='lobby'&&!p} onClick={()=>onTarget(i)}><Flag size={18}/><strong>{n.short}</strong><small>{p?p.name:room&&room.status!=='lobby'?'미참가':n.theory}{p?.isMe?' · 나':''}</small></button>})}<div className="map-legend">N <span>가상 국가 · 교육용 시나리오</span></div></div>}
function Gauge({stat,value}:{stat:Stat;value:number}){const Icon=ICONS[stat];return <div className="stat"><div className="stat-icon"><Icon className="icon-empty"/><span style={{clipPath:`inset(${100-value}% 0 0 0)`}}><Icon/></span></div><div className="stat-label"><span>{STAT_NAMES[stat]}</span><b>{Math.round(value)}<small>/100</small></b><Progress value={value} aria-label={`${STAT_NAMES[stat]} ${Math.round(value)}`} /></div></div>}
function Rules(){return <details className="rules"><summary><BookOpen size={17}/> 플레이 방법과 점수 계산 <ChevronDown size={16}/></summary><div><p><b>① 대기실</b> 방장이 코드를 공유하면 최대 3명이 추가로 참가합니다. 2~4명이 서로 다른 국가를 고르고 모두 준비를 누르면 방장이 시작합니다. 미참가 국가는 지도에 표시되지만 외교·군사 행동의 대상과 순위에서 제외됩니다.</p><p><b>② 매 턴</b> 정책 1개를 선택한 뒤 행동하세요. 모두 동시에 진행하며 시간은 멈추지 않습니다. 국고는 매초 증가하고, 행동은 최대 4개까지 동시에 진행할 수 있습니다. 같은 행동은 턴당 1회, 비밀 전문은 6회 가능합니다.</p><p><b>③ 협상과 결과</b> 협정·비공개 협력·최후통첩은 상대의 수락 또는 거절이 필요합니다. 다음 턴 종료까지 미응답 시 만료됩니다. 행동 비용은 즉시 차감되고 표시된 시간 뒤 효과가 발생합니다. 정책 미선택 시 턴 종료에 지지 −6입니다.</p><p><b>④ 여론과 평가</b> 매 턴 세계 사건이 비용과 능력치를 바꿉니다. 2턴마다 최근 2턴의 공개 행동과 국민 요구를 종합한 규칙 기반 뉴스가 발행되어 지지율을 바꿉니다. 비밀 전문은 기사에 포함되지 않습니다.</p><p><b>⑤ 10턴 종료</b> 번영=(경제+인프라)÷2, 민심=지지, 안보=군사, 외교=관계, 국가 목표=국가별 핵심 능력치. 이 다섯 점수의 평균이 종합 점수입니다. 공동 점수는 공동 순위입니다.</p><p className="muted">각 이론은 학습을 위한 단순화입니다. 국가 성향은 행동을 강제하지 않으며 실제 정치 이론이나 국가를 완전히 설명하지 않습니다. 새로고침하면 같은 브라우저에서 복귀합니다. 접속이 끊겨도 턴 시간은 흐릅니다.</p></div></details>}
export default function Home(){const [room,setRoom]=useState<RoomView|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[connection,setConnection]=useState('연결 중'),[name,setName]=useState(''),[code,setCode]=useState(''),[target,setTarget]=useState(-1),[message,setMessage]=useState(''),[now,setNow]=useState(Date.now()),[offset,setOffset]=useState(0),[copied,setCopied]=useState(false),[war,setWar]=useState(false);const busyRef=useRef(false),inviteRef=useRef(''),generation=useRef(0),roomRef=useRef<RoomView|null>(null);roomRef.current=room;
 const accept=useCallback((r:RoomView|null)=>{setRoom(r);if(r){setOffset(r.serverNow-Date.now());setCode(r.code);}setConnection('동기화됨');},[]);
 const api=useCallback(async(input?:Input)=>{const res=await fetch('/api/game',{method:input?'POST':'GET',cache:'no-store',...(input?{headers:{'Content-Type':'application/json'},body:JSON.stringify({...input,requestId:crypto.randomUUID()})}:{})});const data=await res.json() as {error?:string;room:RoomView|null};if(!res.ok)throw new Error(data.error||'연결에 실패했습니다.');return data.room as RoomView|null;},[]);
 const act=useCallback(async(input:Input)=>{if(busyRef.current)return;busyRef.current=true;generation.current++;setBusy(true);setError('');try{const result=await api({...input,round:roomRef.current?.round,code:input.code||roomRef.current?.code});inviteRef.current='';window.history.replaceState({},'',window.location.pathname);accept(result);if(input.action==='message')setMessage('');}catch(e){setError(e instanceof Error?e.message:'요청을 처리하지 못했습니다.');}finally{busyRef.current=false;setBusy(false);}},[accept,api]);
 useEffect(()=>{let alive=true,timeout:ReturnType<typeof setTimeout>;async function poll(){const version=generation.current;if(!busyRef.current){try{const r=await api();if(alive&&version===generation.current){if(inviteRef.current&&r?.code!==inviteRef.current){accept(null);setCode(inviteRef.current);}else accept(r);}}catch{if(alive)setConnection('연결 재시도 중 · 시간은 계속 흐릅니다');}finally{if(alive)setLoading(false);}}if(alive)timeout=setTimeout(poll,1500);}const param=new URLSearchParams(window.location.search).get('room');if(param){inviteRef.current=param.toUpperCase().slice(0,6);setCode(inviteRef.current);}void poll();const clock=setInterval(()=>setNow(Date.now()),250);return()=>{alive=false;clearTimeout(timeout);clearInterval(clock);};},[api,accept]);
 useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:unknown)=>void}}).modelContext;if(!context)return;const life=new AbortController();try{context.registerTool({name:'read_game_state',description:'현재 참가 중인 국제정치 게임의 공개 상태와 본인의 정보만 읽습니다.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('인수는 빈 객체여야 합니다.');return roomRef.current;}},{signal:life.signal});}catch{ /* Optional browser capability. */ }return()=>life.abort();},[]);
 const me=room?.players.find(p=>p.isMe),nation=me&&me.nation>=0?NATIONS[me.nation]:null;const remaining=room?Math.max(0,Math.ceil((room.deadline-now-offset)/1000)):0;const event=room?EVENTS[room.event]:null;const cost=(a:typeof ACTIONS[number])=>Math.ceil(a.cost*(event?.category===a.category?event.multiplier:1));const send=(action:string)=>void act({type:'action',action,target,text:message});
 async function copy(){try{await navigator.clipboard.writeText(`${location.origin}/?room=${room?.code}`);setCopied(true);setTimeout(()=>setCopied(false),2000);}catch{setError(`방 코드 ${room?.code}를 친구에게 알려 주세요.`);}}
 return <main style={{'--accent':nation?.color||'#edbd67'} as React.CSSProperties}>
 <header className="topbar"><a href="/" className="brand"><Globe2/><span>긴장의 시대<small>THE AGE OF TENSION</small></span></a><div className="top-meta"><span className="edition">2~4인 국제정치 시뮬레이션</span><span className={`connection ${connection==='동기화됨'?'connected':''}`}><Radio size={14}/>{connection}</span></div></header>
 {error&&<div className="error" role="alert"><AlertTriangle size={18}/>{error}<button onClick={()=>setError('')} aria-label="알림 닫기">×</button></div>}
 {loading?<div className="loading"><Globe2 className="spin"/><p>외교 채널을 연결하고 있습니다…</p></div>:!room?<>
 <section className="entry-layout"><div className="entry-panel"><span className="eyebrow">새로운 국제 질서의 시작</span><h1>당신의 선택이<br/>세계의 균형을 바꾼다.</h1><p className="lead">네 국가 중 선택, 열 번의 결정.<br/>협상하고, 투자하고, 당신의 국가를 이끄세요.</p><label htmlFor="name">지도자 이름</label><input id="name" value={name} onChange={e=>setName(e.target.value)} maxLength={16} placeholder="게임에서 사용할 이름" autoComplete="nickname"/><button className="primary full" disabled={busy||!name.trim()} onClick={()=>void act({type:'create',name})}><Flag size={17}/>새 게임 만들기</button><div className="or">또는 초대받은 방에 참가</div><label htmlFor="code">6자리 방 코드</label><div className="join"><input id="code" className="code-input" value={code} onChange={e=>setCode(e.target.value.toUpperCase().replace(/[^A-Z2-9]/g,'').slice(0,6))} maxLength={6} placeholder="ABC234"/><button disabled={busy||!name.trim()||code.length!==6} onClick={()=>void act({type:'join',name,code})}>참가하기</button></div><div className="entry-info"><span><Users size={16}/> 2~4명</span><span><Clock3 size={16}/> 약 15분</span><span><Flag size={16}/> 10턴</span></div></div><div className="entry-world"><WorldMap target={target} onTarget={setTarget}/><div className="nation-intro-grid">{NATIONS.map((n,i)=><button key={n.name} className={`intro-nation ${target===i?'active':''}`} style={{'--nation':n.color} as React.CSSProperties} onClick={()=>setTarget(i)}><div className={`nation-art art-${i}`}/><div><small>{n.theory}</small><strong>{n.short}</strong><span>{n.motto}</span></div></button>)}</div>{target>=0&&<p className="nation-explanation">{NATIONS[target].description}</p>}</div></section><Rules/>
 </>:room.status==='lobby'?<>
 <section className="lobby-heading"><div><span className="eyebrow">외교 회의 대기실</span><h1>당신이 이끌 국가를 선택하세요.</h1><p>각 국가는 한 명만 선택할 수 있습니다. 2명 이상 참가하고 모두 준비하면 시작할 수 있습니다.</p></div><button className="room-code" onClick={copy}><span>초대 코드</span><b>{room.code}</b>{copied?<Check size={18}/>:<Copy size={18}/>}</button></section>
 <div className="lobby-toolbar"><span><Users size={18}/> 참가자 <b>{room.players.length} / 4</b></span><div className="duration"><Clock3 size={17}/><span>턴 시간</span><Select value={String(room.duration)} disabled={!room.isHost||busy} onValueChange={v=>void act({type:'duration',duration:Number(v)})}><SelectTrigger aria-label="턴 시간"><SelectValue/></SelectTrigger><SelectContent>{[60,90,120].map(s=><SelectItem key={s} value={String(s)}>{s}초</SelectItem>)}</SelectContent></Select></div><button className="text-button" disabled={busy} onClick={()=>void act({type:'leave'})}><LogOut size={16}/> 나가기</button></div>
 <section className="nation-grid">{NATIONS.map((n,i)=>{const owner=room.players.find(p=>p.nation===i);return <article key={n.name} className={`nation-card ${me?.nation===i?'selected':''}`} style={{'--nation':n.color} as React.CSSProperties}><div className={`nation-art art-${i}`}><span className="theory-chip">{n.theory}</span><span className="region">{n.region}</span></div><div className="nation-body"><div className="nation-title"><Flag size={18}/><h2>{n.name}</h2></div><p className="motto">“{n.motto}”</p><p className="description">{n.description}</p><div className="mini-stats">{(Object.keys(STAT_NAMES) as Stat[]).map(k=><Gauge key={k} stat={k} value={n.stats[k]}/>)}</div><div className="nation-goal">국민 요구 <b>{n.want}</b></div><div className="starting-gold"><Coins size={16}/> 시작 국고 <b>{n.money}</b></div><button className={`full ${me?.nation===i?'primary':''}`} disabled={busy||!!owner&&!owner.isMe} onClick={()=>void act({type:'select',nation:i})}>{owner?`${owner.name}${owner.ready?' · 준비 완료':owner.isMe?' · 선택됨':' · 선택 중'}`:'이 국가 선택'}</button></div></article>})}</section>
 <div className="ready-bar"><div className="players-list">{room.players.map((p,i)=><span key={i}><span className={p.online?'presence on':'presence'}/>{p.name}{p.isHost?' (방장)':''}{p.ready?<Check size={15}/>:<small>준비 중</small>}</span>)}</div><div className="ready-buttons"><button disabled={busy||(me?.nation??-1)<0} onClick={()=>void act({type:'ready'})}>{me?.ready?'준비 취소':'준비 완료'}</button>{room.isHost&&<button className="primary" disabled={busy||!canStart(room.players)} onClick={()=>void act({type:'start'})}>게임 시작</button>}</div></div><Rules/>
 </>:<>
 <div className="game-topline"><div><span className="eyebrow">{room.status==='finished'?'최종 보고서':'국가 운영 본부'}</span><h1>{nation?.name}</h1></div><div className="game-counters"><div><span>ROUND</span><strong>{String(room.round).padStart(2,'0')}<small>/10</small></strong></div><div className={remaining<15&&room.status==='playing'?'urgent':''}><span><Clock3 size={14}/> 남은 시간</span><strong>{room.status==='finished'?'종료':`${Math.floor(remaining/60)}:${String(remaining%60).padStart(2,'0')}`}</strong></div><div><span><Coins size={14}/> 국고</span><strong>{me?.money}<small> G</small></strong></div></div></div>
 {room.status==='finished'&&<section className="results panel"><div className="section-heading"><h2><Trophy/> 10턴, 당신이 만든 세계</h2><button disabled={busy} onClick={()=>void act({type:'create',name:me?.name})} className="text-button">새 방 만들기</button></div><p>종합 점수는 다섯 분야의 평균입니다. 국가 목표는 선택한 국가의 핵심 능력치입니다.</p><div className="score-grid">{room.scores.map((s,i)=><article key={s.nation} style={{'--nation':NATIONS[s.nation].color} as React.CSSProperties}><span className="rank">{room.scores.findIndex(x=>x.total===s.total)+1}위</span><h3>{NATIONS[s.nation].short}</h3><p>{s.name}</p><strong className="score-total">{s.total}<small>점</small></strong><dl>{[['번영',s.prosperity],['민심',s.stability],['안보',s.security],['외교',s.diplomacy],['국가 목표',s.goal]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><p className="muted">{s.style}</p></article>)}</div></section>}
 <div className="game-layout"><aside className="national-panel panel"><div className={`nation-art art-${me?.nation}`}><span className="theory-chip">{nation?.theory}</span><strong>{nation?.motto}</strong></div><div className="national-content"><h2>국가 현황 <span>{me?.name}</span></h2>{me&&(Object.keys(STAT_NAMES) as Stat[]).map(k=><Gauge key={k} stat={k} value={me.stats[k]}/>)}<div className="nation-goal">국민 요구 <b>{nation?.want}</b></div><p className="income">초당 +{me?(.28+me.stats.economy/150+me.stats.infrastructure/300+(me.nation===2?.1:0)).toFixed(2):0} G <small>경제·인프라가 높을수록 증가</small></p><div className="tension"><span><Activity size={16}/> 세계 긴장도 <b>{Math.round(room.tension)}</b></span><Progress value={room.tension} aria-label={`세계 긴장도 ${room.tension}`}/><small>{room.tension>=70?'위기 고조':room.tension>=35?'불안정한 균형':'협력의 기회'}</small></div><p className="muted">방 코드 <b>{room.code}</b></p></div></aside>
 <div className="main-command"><WorldMap room={room} target={target} onTarget={setTarget}/><section className="world-event"><span><Radio size={18}/> 이번 턴 세계 사건</span><h2>{event?.title}</h2><p>{event?.description}</p>{room.players.length<4&&<p className="muted">공통 효과는 모든 참가국에 적용됩니다. 특정 국가의 추가 효과는 해당 국가가 참가한 경우에 적용됩니다.</p>}</section>
 {room.status==='playing'&&me?.choice===null?<section className="policy panel"><div className="section-heading"><h2>01 <span>이번 턴의 정책 결정</span></h2><span className="badge">먼저 1개 선택</span></div><p>세계 사건과 국민 요구를 고려해 방향을 정하세요.</p><div className="choice-grid">{CHOICES[me.nation].map((c,i)=><button disabled={busy||me.money+(c.effect.money||0)<0} onClick={()=>void act({type:'choice',choice:i})} key={i}><span>0{i+1}</span><h3>{c.label}</h3><p>{c.detail}</p><small>세계 긴장 {c.tension>0?'+':''}{c.tension}</small></button>)}</div></section>:room.status==='playing'&&<section className="chosen-policy"><Check size={17}/><span>이번 턴 정책</span><b>{CHOICES[me!.nation][me!.choice!]?.label}</b></section>}
 <section className="actions panel"><div className="section-heading"><h2>02 <span>국가 행동</span></h2><span className="muted">동시 진행 {room.jobs.length}/4</span></div><div className="target-select"><span>대상 국가</span><Select value={target>=0&&target!==me?.nation&&room.players.some(p=>p.nation===target)?String(target):''} onValueChange={v=>setTarget(Number(v))}><SelectTrigger aria-label="대상 국가 선택"><SelectValue placeholder="다른 국가 선택"/></SelectTrigger><SelectContent>{NATIONS.filter((_,i)=>i!==me?.nation&&room.players.some(p=>p.nation===i)).map(n=><SelectItem key={n.name} value={String(NATIONS.indexOf(n))}>{n.name}</SelectItem>)}</SelectContent></Select></div><Tabs defaultValue="public"><TabsList className="action-tabs"><TabsTrigger value="public"><Globe2/>공개 행동</TabsTrigger><TabsTrigger value="secret"><LockKeyhole/>비밀 외교</TabsTrigger><TabsTrigger value="military"><Shield/>군사 행동</TabsTrigger><TabsTrigger value="domestic"><Landmark/>국내 행동</TabsTrigger></TabsList>{['public','secret','military','domestic'].map(category=><TabsContent key={category} value={category}>{category==='secret'&&<div className="message-field"><label htmlFor="message">비밀 전문 · 상대와 나만 열람</label><textarea id="message" value={message} onChange={e=>setMessage(e.target.value)} maxLength={240} placeholder="협상 내용이나 제안을 작성하세요."/><small>{message.length}/240</small></div>}<div className="action-grid">{ACTIONS.filter(a=>a.category===category).map(a=>{const disabled=busy||room.status!=='playing'||me?.choice===null||(me?.money||0)<cost(a)||!!me?.used[a.id]&&(a.id!=='message'||me.used.message>=6)||!!a.target&&(target<0||target===me?.nation||!room.players.some(p=>p.nation===target))||remaining<a.seconds||(a.id==='message'&&!message.trim())||room.jobs.length>=4;return <button className={`action-button ${a.id==='war'?'danger':''}`} key={a.id} disabled={disabled} onClick={()=>a.id==='war'?setWar(true):send(a.id)}><div><strong>{a.name}</strong><span><Coins size={13}/>{cost(a)} <Clock3 size={13}/>{a.seconds}초</span></div><p>{a.description}</p>{me?.used[a.id]&&a.id!=='message'?<small><Check size={12}/> 이번 턴 실행함</small>:null}</button>})}</div></TabsContent>)}</Tabs>{room.status==='playing'&&me?.choice===null&&<p className="muted">정책을 선택하면 행동할 수 있습니다.</p>}</section>
 </div><aside className="dispatch-column"><section className="panel queue"><h2><Clock3 size={18}/> 진행 중인 행동</h2>{room.jobs.length?room.jobs.map(j=><div className="job" key={j.id}><b>{ACTIONS.find(a=>a.id===j.action)?.name}</b><span>{Math.max(0,Math.ceil((j.end-now-offset)/1000))}초</span><Progress value={Math.max(0,Math.min(100,(now+offset-j.start)/(j.end-j.start)*100))} aria-label="행동 진행률"/></div>):<p className="empty-text">진행 중인 행동이 없습니다.<br/>행동을 선택하면 여기에 표시됩니다.</p>}</section><section className="panel diplomacy"><h2><Handshake size={18}/> 외교 수신함</h2>{room.offers.filter(o=>o.to===me?.nation&&o.status==='pending').length?room.offers.filter(o=>o.to===me?.nation&&o.status==='pending').map(o=><article className="offer" key={o.id}><small>{NATIONS[o.from].short}에서 도착</small><h3>{ACTIONS.find(a=>a.id===o.kind)?.name}</h3><p>{o.kind==='treaty'?'수락하면 양국 경제 +10, 관계 +8':o.kind==='backchannel'?'비공개 · 양국 국고 +15, 관계 +6':'양보하면 국고 최대 20 이전, 지지 −7. 거부하면 지지 +4, 긴장 +6.'}</p><small>남은 시간 {Math.max(0,Math.ceil((o.expires-now-offset)/1000))}초</small><div><button disabled={busy} onClick={()=>void act({type:'respond',offerId:o.id,accept:false})}>거절</button><button className="primary" disabled={busy} onClick={()=>void act({type:'respond',offerId:o.id,accept:true})}>{o.kind==='ultimatum'?'양보':'수락'}</button></div></article>):<p className="empty-text">응답을 기다리는 제안이 없습니다.</p>}</section><section className="panel nations-status"><h2><Users size={18}/> 참가 국가</h2>{room.players.map(p=><div key={p.nation}><span className={p.online?'presence on':'presence'}/><strong style={{color:NATIONS[p.nation].color}}>{NATIONS[p.nation].short}</strong><small>{p.isMe?'나':p.online?'접속 중':'연결 끊김'}</small><div>경제 {p.stats.economy} · 군사 {p.stats.military} · 관계 {p.stats.relations}</div></div>)}</section></aside></div>
 <section className="report-grid"><div className="panel newspaper"><div className="section-heading"><h2>THE ARDEN TIMES</h2><span>2턴마다 발행</span></div>{room.news.length?[...room.news].reverse().map((n,i)=><details key={n.round} open={i===0}><summary><span>{n.round-1}–{n.round}턴 국제 뉴스</span><h3>{n.title}</h3></summary><p>{n.body}</p><div className="news-impacts">{n.impacts.map(impact=><div key={impact.nation}><b>{NATIONS[impact.nation].short}</b><strong className={impact.delta>=0?'positive':'negative'}>지지 {impact.delta>0?'+':''}{impact.delta}</strong><small>{impact.reason}</small></div>)}</div></details>):<div className="newspaper-empty"><Radio size={26}/><h3>첫 기사는 2턴 종료 후 발행됩니다.</h3><p>정책과 외교, 충돌과 협력이 모여 기사가 됩니다.<br/>기사에 반영된 여론은 국민 지지율을 바꿉니다.</p></div>}</div><div className="panel logs"><h2>외교·행동 기록</h2><Tabs defaultValue="public"><TabsList><TabsTrigger value="public">공개 기록</TabsTrigger><TabsTrigger value="secret"><LockKeyhole size={13}/>비밀 전문</TabsTrigger></TabsList>{['public','secret'].map(t=><TabsContent key={t} value={t}><div className="log-list">{[...room.logs].reverse().filter(l=>t==='secret'?l.privateTo:!l.privateTo).map(l=><article key={l.id}><small>TURN {String(l.round).padStart(2,'0')}{l.privateTo?' · 비공개':''}</small><p>{l.text}</p></article>)}{!room.logs.some(l=>t==='secret'?l.privateTo:!l.privateTo)&&<p className="empty-text">아직 기록이 없습니다.</p>}</div></TabsContent>)}</Tabs></div></section><Rules/>
 </>}
 <footer><span>긴장의 시대</span><span>2~4인 동시 진행 · 4개 국가 · 10턴의 국제정치</span></footer>
 <AlertDialog open={war} onOpenChange={setWar}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{target>=0?NATIONS[target].short:''}에 전쟁을 선포합니까?</AlertDialogTitle><AlertDialogDescription>전쟁은 양국의 군사력·경제·인프라에 피해를 줍니다. 공격국의 국제 관계가 22 감소하고 세계 긴장도가 22 증가합니다. 비용은 즉시 지불하며 취소할 수 없습니다.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>돌아가기</AlertDialogCancel><AlertDialogAction onClick={()=>send('war')}>전쟁 선포</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </main>;
}
