import {database} from '@/db';
import {cleanName,command,createRoom,GameError,Room,view,Command} from '@/lib/game';
const headers={'Cache-Control':'no-store, private','Content-Type':'application/json; charset=utf-8'};
function cookies(req:Request){return Object.fromEntries((req.headers.get('cookie')||'').split(';').map(x=>{const i=x.indexOf('=');return [x.slice(0,i).trim(),x.slice(i+1).trim()];}));}
async function identity(token:string){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(token)))).map(x=>x.toString(16).padStart(2,'0')).join('');}
function rawReply(value:unknown,token?:string,code?:string,status=200,secure=true){const h=new Headers(headers);if(token)h.append('Set-Cookie',`tension_session=${token}; Path=/; HttpOnly; SameSite=Lax; Max-Age=604800${secure?"; Secure":""}`);if(code)h.append('Set-Cookie',`tension_room=${code}; Path=/; HttpOnly; SameSite=Lax; Max-Age=604800${secure?"; Secure":""}`);return new Response(JSON.stringify(value),{status,headers:h});}
async function handle(req:Request){const respond=(value:unknown,token?:string,code?:string,status=200)=>rawReply(value,token,code,status,new URL(req.url).protocol==="https:");try{const url=new URL(req.url),cs=cookies(req);let token=cs.tension_session;const existing=!!token&&/^[a-f0-9]{64}$/.test(token);if(!existing)token=Array.from(crypto.getRandomValues(new Uint8Array(32))).map(n=>n.toString(16).padStart(2,'0')).join('');const id=await identity(token);const now=Date.now();let body:Command&{code?:string}={type:'heartbeat'};
 if(req.method==='POST'){const origin=req.headers.get('origin');if(origin&&origin!==url.origin)return respond({error:'다른 사이트에서 보낸 요청입니다.'},undefined,undefined,403);if(!req.headers.get('content-type')?.includes('application/json'))return respond({error:'JSON 요청이 필요합니다.'},undefined,undefined,415);const raw=await req.text();if(raw.length>4096)return respond({error:'요청이 너무 큽니다.'},undefined,undefined,413);try{body=JSON.parse(raw);}catch{throw new GameError('올바르지 않은 요청입니다.');}if(!body||typeof body.type!=='string')throw new GameError('요청 종류가 필요합니다.');if(body.requestId!==undefined&&(typeof body.requestId!=='string'||body.requestId.length>80))throw new GameError('요청 번호가 올바르지 않습니다.');}
 const db=database();let code=(body.code||url.searchParams.get('code')||cs.tension_room||'');if(typeof code!=='string')throw new GameError('방 코드를 확인해 주세요.');code=code.trim().toUpperCase();
 if(req.method==='POST'&&body.type==='create'){const name=cleanName(body.name);if(existing&&cs.tension_room){const current=await db.prepare('SELECT state FROM game_rooms WHERE code = ?').bind(cs.tension_room).first<{state:string}>();if(current){const old=JSON.parse(current.state) as Room;if(old.status==='lobby'&&old.players.some(p=>p.id===id)){throw new GameError('현재 대기실에서 나간 뒤 새 방을 만들어 주세요.');}}}const alphabet='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';for(let attempt=0;attempt<5;attempt++){const bytes=crypto.getRandomValues(new Uint8Array(6));code=Array.from(bytes,x=>alphabet[x%alphabet.length]).join('');const room=createRoom(code,id,name,now);const out=await db.prepare('INSERT OR IGNORE INTO game_rooms (code,state,revision,updated) VALUES (?,?,0,?)').bind(code,JSON.stringify(room),now).run();if(out.meta.changes)return respond({room:view(room,id,now)},token,code);}throw new Error('Room code allocation failed');}
 if(!code&&req.method==='GET')return respond({room:null},undefined);if(!/^[A-Z2-9]{6}$/.test(code))throw new GameError('6자리 방 코드를 입력해 주세요.');if(!existing&&req.method==='GET')return respond({room:null});
 for(let attempt=0;attempt<8;attempt++){const row=await db.prepare('SELECT state,revision FROM game_rooms WHERE code = ?').bind(code).first<{state:string;revision:number}>();if(!row){if(req.method==='GET'&&!url.searchParams.get('code'))return respond({room:null});throw new GameError('방을 찾을 수 없습니다. 코드를 확인해 주세요.');}const room=JSON.parse(row.state) as Room;
 if(req.method==='GET'&&!room.players.some(p=>p.id===id)&&!url.searchParams.get('code'))return respond({room:null});
 command(room,id,body,now);const result=await db.prepare('UPDATE game_rooms SET state = ?, revision = revision + 1, updated = ? WHERE code = ? AND revision = ?').bind(JSON.stringify(room),now,code,row.revision).run();if(result.meta.changes)return respond({room:body.type==='leave'?null:view(room,id,now)},existing?undefined:token,code);}
 return respond({error:'동시에 처리 중인 요청이 많습니다. 잠시 후 다시 시도해 주세요.'},undefined,undefined,409);
 }catch(error){if(error instanceof GameError)return respond({error:error.message},undefined,undefined,400);console.error('game request failed',error);return respond({error:'게임 서버에 연결하지 못했습니다. 입력을 유지했으니 다시 시도해 주세요.'},undefined,undefined,503);}}
export const GET=handle;
export const POST=handle;
