import assert from 'node:assert/strict';
import {createRoom,command,tick,view,GameError,ACTIONS,NATIONS,EVENTS,CHOICES,score,income,POLICY_SECONDS} from '../lib/game.ts';
const t=1000000;
export function ready(nations=[0,1,2,3],seed=42){const r=createRoom('TEST23','p0','host',t);r.seed=seed;for(let i=0;i<nations.length;i++){if(i)command(r,`p${i}`,{type:'join',name:`guest${i}`},t);command(r,`p${i}`,{type:'select',nation:nations[i]},t);command(r,`p${i}`,{type:'ready'},t);}return r;}
function started(nations=[0,1,2,3]){const r=ready(nations);command(r,'p0',{type:'start'},t);return r;}
const solo=ready([3]);assert.throws(()=>command(solo,'p0',{type:'start'},t),/2~4명/);
for(const nations of [[3,1],[2,0,3],[0,1,2,3]]){
 const r=ready(nations);command(r,'p1',{type:'ready'},t);assert.throws(()=>command(r,'p0',{type:'start'},t),/준비/);command(r,'p1',{type:'ready'},t);assert.throws(()=>command(r,'p1',{type:'start'},t),/방장/);command(r,'p0',{type:'start'},t);
 assert.throws(()=>command(r,'outsider',{type:'action',action:'economy'},t),GameError);assert.throws(()=>command(r,'late',{type:'join',name:'late'},t),/이미 시작/);
 assert.throws(()=>command(r,'p0',{type:'action',action:'economy'},t),/정책/);
 for(const p of r.players)command(r,p.id,{type:'choice',choice:-1},t);
 const p=r.players[0],old=p.stats.support;assert.equal(p.choice,-1);assert.equal(p.stats.support,old);
 if(nations.length<4){const absent=[0,1,2,3].find(n=>!nations.includes(n));const gold=p.money;assert.throws(()=>command(r,'p0',{type:'action',action:'aid',target:absent},t),/대상/);assert.equal(p.money,gold);}
 command(r,'p0',{type:'action',action:'message',target:nations[1],text:'SECRET_CHANNEL'},t);assert(!view(r,'p1',t).logs.some(l=>l.text.includes('SECRET_CHANNEL')));tick(r,t+5000);assert(view(r,'p1',t+5000).logs.some(l=>l.text.includes('SECRET_CHANNEL')));if(nations.length>2)assert(!JSON.stringify(view(r,'p2',t+5000)).includes('SECRET_CHANNEL'));
 tick(r,t+900000);assert.equal(r.status,'finished');assert.equal(r.news.length,5);assert.equal(view(r,'p0',t+900000).scores.length,nations.length);assert(r.news.every(n=>n.impacts.length===nations.length));
 const end=JSON.stringify(r.players);tick(r,t+999000);assert.equal(JSON.stringify(r.players),end);for(const player of r.players){assert(Object.values(player.stats).every(x=>x>=0&&x<=100));assert(score(player).total>=0&&score(player).total<=100);}
}
const policy=started();const before={...policy.players[0].stats},cash=policy.players[0].money;command(policy,'p0',{type:'choice',choice:0,requestId:'policy'},t);assert.deepEqual(policy.players[0].stats,before);assert.equal(policy.players[0].money,cash-25);command(policy,'p0',{type:'choice',choice:0,requestId:'policy'},t);assert.equal(policy.jobs.filter(j=>j.action==='policy').length,1);tick(policy,t+POLICY_SECONDS*1000-1);assert.deepEqual(policy.players[0].stats,before);tick(policy,t+POLICY_SECONDS*1000);assert.equal(policy.players[0].stats.military,Math.min(100,before.military+16));
const cross=started();for(const p of cross.players){p.money=1000;command(cross,p.id,{type:'choice',choice:-1},t);}const start=t+80000;command(cross,'p0',{type:'action',action:'economy',requestId:'invest'},start);const balance=cross.players[0].money;command(cross,'p0',{type:'action',action:'economy',requestId:'invest'},start);assert.equal(cross.players[0].money,balance);assert.equal(cross.jobs.length,1);assert.throws(()=>command(cross,'p0',{type:'action',action:'economy'},start),/진행 중/);tick(cross,t+90000);assert.equal(cross.round,2);assert.equal(cross.jobs.length,1);command(cross,'p0',{type:'choice',choice:-1},t+90000);tick(cross,t+115000);assert.equal(cross.jobs.length,0);command(cross,'p0',{type:'action',action:'economy'},t+115000);assert.equal(cross.jobs.length,1);
for(const a of ACTIONS){const r=started([3,1]);for(const p of r.players){p.money=1000;command(r,p.id,{type:'choice',choice:-1},t);}command(r,'p0',{type:'action',action:a.id,target:1,text:'확인',topic:'trade'},t);assert.equal(r.jobs.length,1);tick(r,t+a.seconds*1000);assert(r.logs.some(l=>l.actor===3&&(l.kind===a.id||['treaty','backchannel','ultimatum'].includes(a.id)&&l.kind==='offer')));if(a.id==='war')r.players[0].stats.military=80;command(r,'p0',{type:'action',action:a.id,target:1,text:'다시',topic:'trade'},t+a.seconds*1000);assert.equal(r.jobs.length,1);}
assert.equal(ACTIONS.length,12);assert.equal(EVENTS.length,13);assert.deepEqual(CHOICES.map(c=>c.length),[3,3,3,3]);
for(let event=0;event<EVENTS.length;event++){let seed=0;while(Math.floor(((Math.imul(1664525,seed)+1013904223)>>>0)/4294967296*EVENTS.length)!==event)seed+=65537;const r=ready([3,1],seed);command(r,'p0',{type:'start'},t);assert.equal(r.event,event);assert(r.bulletins.length);for(const p of r.players)for(const stat of Object.keys(p.stats)){const e=EVENTS[event];assert.equal(p.stats[stat],Math.max(0,Math.min(100,NATIONS[p.nation].stats[stat]+(e.effect[stat]||0)+(p.nation===e.nation?(e.local[stat]||0):0))));}}
const lobby=ready([0,1]);command(lobby,'p0',{type:'leave'},t);assert.equal(lobby.host,'p1');
for(const n of NATIONS){const p={nation:NATIONS.indexOf(n),stats:n.stats};const old=.28+n.stats.economy/150+n.stats.infrastructure/300+(p.nation===2?.1:0);assert(income(p)<old*.21);assert(income(p)>0);}
console.log('PASS: 2–4 players, host/readiness/absent targets, policy hold and delayed enactment, idempotency, repeated and cross-turn actions, 13 events, all 12 actions, private messages, 10-turn scoring, reduced income');
