import assert from 'node:assert/strict';
import {createRoom,command,tick,view,EVENTS,COOPERATION,POLICY_OPINIONS,relationLabel,income,describeEffect,eventDescription,actionDescription,ACTIONS} from '../lib/game.ts';
const t=1000000;
function game(nations=[0,1,2,3],seed=42){const r=createRoom('NEWS23','p0','host',t);r.seed=seed;for(let i=0;i<nations.length;i++){if(i)command(r,`p${i}`,{type:'join',name:`guest${i}`},t);command(r,`p${i}`,{type:'select',nation:nations[i]},t);command(r,`p${i}`,{type:'ready'},t);}command(r,'p0',{type:'start'},t);for(const p of r.players){p.money=1000;command(r,p.id,{type:'choice',choice:-1},t);}return r;}
for(const count of [2,3,4]){const r=game([0,1,2,3].slice(0,count));assert.equal(r.relations.length,count*(count-1)/2);const next=r.nextEvent;tick(r,t+90000);assert.equal(r.event,next);for(const n of r.bulletins){assert.equal(n.editions.length,count);for(const e of n.editions){assert(!/[+−]\s*\d/.test(JSON.stringify(e.articles)));assert.equal(e.figures.worldDeaths,r.players.reduce((v,p)=>v+(p.deaths||0),0));}}}
for(const topic of COOPERATION){const r=game();command(r,'p0',{type:'action',action:'treaty',target:1,topic:topic.id},t);tick(r,t+20000);const offer=r.offers[0],cash=r.players[1].money;assert.equal(offer.topic,topic.id);assert.throws(()=>command(r,'p2',{type:'respond',offerId:offer.id,accept:true},t+20000),/응답/);r.players[1].money=0;assert.throws(()=>command(r,'p1',{type:'respond',offerId:offer.id,accept:true},t+20000),/예산/);assert.equal(offer.status,'pending');r.players[1].money=cash;command(r,'p1',{type:'respond',offerId:offer.id,accept:true},t+20000);assert.equal(r.players[1].money,cash-topic.contribution);assert.equal(r.relations.find(x=>x.a===0&&x.b===1).label,'협력');assert(r.players[0].prepared[topic.protection]>0);}
const hostile=game();command(hostile,'p0',{type:'action',action:'treaty',target:1,topic:'trade'},t);tick(hostile,t+20000);command(hostile,'p1',{type:'respond',offerId:hostile.offers[0].id,accept:true},t+20000);command(hostile,'p0',{type:'action',action:'sanction',target:1},t+21000);tick(hostile,t+53000);assert(hostile.boycotts.some(x=>x.from===1&&x.target===0));assert(hostile.bulletins.some(x=>x.title.includes('불매')));assert(income(hostile.players[0],hostile)<income(hostile.players[0]));assert(hostile.reactions.some(x=>x.text.includes('불매')||x.text.includes('안 사겠습니다')));
const secret=game();command(secret,'p0',{type:'action',action:'backchannel',target:1,topic:'health'},t);tick(secret,t+24000);const baseline=secret.bulletins.length;command(secret,'p1',{type:'respond',offerId:secret.offers[0].id,accept:true},t+24000);const outsider=view(secret,'p2',t+24000);assert.equal(secret.bulletins.length,baseline);assert(!outsider.offers.some(x=>x.kind==='backchannel'));assert(outsider.reactions.every(x=>!x.privateTo));assert.equal(outsider.players.find(p=>p.nation===0).prepared,undefined);assert(secret.relations.every(x=>x.value===0));
const a=game(),b=structuredClone(a);b.players[0].prepared={health:44};a.nextEvent=b.nextEvent=2;tick(a,t+90000);tick(b,t+90000);assert(b.players[0].deaths<a.players[0].deaths);assert.equal(a.pandemicAt,t+90000);a.nextEvent=2;tick(a,t+180000);assert.equal(a.pandemicAt,t+90000);const latest=a.bulletins.at(-1).editions[0];assert.equal(latest.figures.deaths,a.players[0].deaths);assert.equal(latest.figures.worldDeaths,a.players.reduce((n,p)=>n+(p.deaths||0),0));
const poor=game([3,1]);delete poor.relations;delete poor.reactions;delete poor.bulletins;delete poor.pressCooldown;delete poor.boycotts;assert.doesNotThrow(()=>view(poor,'p0',t));
assert.deepEqual([-80,-20,0,20,50].map(relationLabel),['충돌','긴장','중립','우호','협력']);assert.equal(POLICY_OPINIONS.flat().length,12);assert(POLICY_OPINIONS.flat().every(x=>x.length===3));assert(!/[+−]\d/.test(describeEffect({economy:16,money:-30})));for(const e of EVENTS)assert(!/[+−]\s*\d/.test(eventDescription(e)));for(const a of ACTIONS)assert(!/[+−]\s*\d/.test(actionDescription(a.id)));
console.log('PASS: nation editions, forecasts, five cooperation fields and contribution gates, hidden private cooperation, boycott news and income penalty, crisis mitigation and exact fictional harm totals, opinion data and qualitative effect copy');
